//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 10:17:24 AM CEST 
//


package cz.cuni.mff.been.jaxb.td;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import cz.cuni.mff.been.jaxb.AbstractSerializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://been.mff.cuni.cz/taskmanager/td}description" minOccurs="0"/>
 *         &lt;element ref="{http://been.mff.cuni.cz/taskmanager/td}arguments" minOccurs="0"/>
 *         &lt;element ref="{http://been.mff.cuni.cz/taskmanager/td}java" minOccurs="0"/>
 *         &lt;element ref="{http://been.mff.cuni.cz/taskmanager/td}taskProperties" minOccurs="0"/>
 *         &lt;element ref="{http://been.mff.cuni.cz/taskmanager/td}taskPropertyObjects" minOccurs="0"/>
 *         &lt;element ref="{http://been.mff.cuni.cz/taskmanager/td}package"/>
 *         &lt;element ref="{http://been.mff.cuni.cz/taskmanager/td}hostRuntimes"/>
 *         &lt;element ref="{http://been.mff.cuni.cz/taskmanager/td}dependencies" minOccurs="0"/>
 *         &lt;element ref="{http://been.mff.cuni.cz/taskmanager/td}failurePolicy" minOccurs="0"/>
 *         &lt;element ref="{http://been.mff.cuni.cz/taskmanager/td}loadMonitoring" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attGroup ref="{http://been.mff.cuni.cz/taskmanager/td}taskDescriptorAttrGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "taskDescriptor")
public class TaskDescriptor
    extends AbstractSerializable
    implements Serializable
{

    private final static long serialVersionUID = -9223372036854775808L;
    @XmlElement(name = "description")
    protected String longDescription;
    protected Arguments arguments;
    protected Java java;
    protected TaskProperties taskProperties;
    protected TaskPropertyObjects taskPropertyObjects;
    @XmlElement(name = "package", required = true)
    protected Package _package;
    @XmlElement(required = true)
    protected HostRuntimes hostRuntimes;
    protected Dependencies dependencies;
    protected FailurePolicy failurePolicy;
    protected LoadMonitoring loadMonitoring;
    @XmlAttribute(name = "taskId", required = true)
    protected String taskId;
    @XmlAttribute(name = "contextId", required = true)
    protected String contextId;
    @XmlAttribute(name = "treeAddress", required = true)
    protected String treeAddress;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "exclusive")
    protected TaskExclusivity exclusive;

    /**
     * Gets the value of the longDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongDescription() {
        return longDescription;
    }

    /**
     * Sets the value of the longDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongDescription(String value) {
        this.longDescription = value;
    }

    public boolean isSetLongDescription() {
        return (this.longDescription!= null);
    }

    /**
     * Gets the value of the arguments property.
     * 
     * @return
     *     possible object is
     *     {@link Arguments }
     *     
     */
    public Arguments getArguments() {
        return arguments;
    }

    /**
     * Sets the value of the arguments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Arguments }
     *     
     */
    public void setArguments(Arguments value) {
        this.arguments = value;
    }

    public boolean isSetArguments() {
        return (this.arguments!= null);
    }

    /**
     * Gets the value of the java property.
     * 
     * @return
     *     possible object is
     *     {@link Java }
     *     
     */
    public Java getJava() {
        return java;
    }

    /**
     * Sets the value of the java property.
     * 
     * @param value
     *     allowed object is
     *     {@link Java }
     *     
     */
    public void setJava(Java value) {
        this.java = value;
    }

    public boolean isSetJava() {
        return (this.java!= null);
    }

    /**
     * Gets the value of the taskProperties property.
     * 
     * @return
     *     possible object is
     *     {@link TaskProperties }
     *     
     */
    public TaskProperties getTaskProperties() {
        return taskProperties;
    }

    /**
     * Sets the value of the taskProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskProperties }
     *     
     */
    public void setTaskProperties(TaskProperties value) {
        this.taskProperties = value;
    }

    public boolean isSetTaskProperties() {
        return (this.taskProperties!= null);
    }

    /**
     * Gets the value of the taskPropertyObjects property.
     * 
     * @return
     *     possible object is
     *     {@link TaskPropertyObjects }
     *     
     */
    public TaskPropertyObjects getTaskPropertyObjects() {
        return taskPropertyObjects;
    }

    /**
     * Sets the value of the taskPropertyObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskPropertyObjects }
     *     
     */
    public void setTaskPropertyObjects(TaskPropertyObjects value) {
        this.taskPropertyObjects = value;
    }

    public boolean isSetTaskPropertyObjects() {
        return (this.taskPropertyObjects!= null);
    }

    /**
     * Gets the value of the package property.
     * 
     * @return
     *     possible object is
     *     {@link Package }
     *     
     */
    public Package getPackage() {
        return _package;
    }

    /**
     * Sets the value of the package property.
     * 
     * @param value
     *     allowed object is
     *     {@link Package }
     *     
     */
    public void setPackage(Package value) {
        this._package = value;
    }

    public boolean isSetPackage() {
        return (this._package!= null);
    }

    /**
     * Gets the value of the hostRuntimes property.
     * 
     * @return
     *     possible object is
     *     {@link HostRuntimes }
     *     
     */
    public HostRuntimes getHostRuntimes() {
        return hostRuntimes;
    }

    /**
     * Sets the value of the hostRuntimes property.
     * 
     * @param value
     *     allowed object is
     *     {@link HostRuntimes }
     *     
     */
    public void setHostRuntimes(HostRuntimes value) {
        this.hostRuntimes = value;
    }

    public boolean isSetHostRuntimes() {
        return (this.hostRuntimes!= null);
    }

    /**
     * Gets the value of the dependencies property.
     * 
     * @return
     *     possible object is
     *     {@link Dependencies }
     *     
     */
    public Dependencies getDependencies() {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dependencies }
     *     
     */
    public void setDependencies(Dependencies value) {
        this.dependencies = value;
    }

    public boolean isSetDependencies() {
        return (this.dependencies!= null);
    }

    /**
     * Gets the value of the failurePolicy property.
     * 
     * @return
     *     possible object is
     *     {@link FailurePolicy }
     *     
     */
    public FailurePolicy getFailurePolicy() {
        return failurePolicy;
    }

    /**
     * Sets the value of the failurePolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link FailurePolicy }
     *     
     */
    public void setFailurePolicy(FailurePolicy value) {
        this.failurePolicy = value;
    }

    public boolean isSetFailurePolicy() {
        return (this.failurePolicy!= null);
    }

    /**
     * Gets the value of the loadMonitoring property.
     * 
     * @return
     *     possible object is
     *     {@link LoadMonitoring }
     *     
     */
    public LoadMonitoring getLoadMonitoring() {
        return loadMonitoring;
    }

    /**
     * Sets the value of the loadMonitoring property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadMonitoring }
     *     
     */
    public void setLoadMonitoring(LoadMonitoring value) {
        this.loadMonitoring = value;
    }

    public boolean isSetLoadMonitoring() {
        return (this.loadMonitoring!= null);
    }

    /**
     * Gets the value of the taskId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * Sets the value of the taskId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskId(String value) {
        this.taskId = value;
    }

    public boolean isSetTaskId() {
        return (this.taskId!= null);
    }

    /**
     * Gets the value of the contextId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextId() {
        return contextId;
    }

    /**
     * Sets the value of the contextId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextId(String value) {
        this.contextId = value;
    }

    public boolean isSetContextId() {
        return (this.contextId!= null);
    }

    /**
     * Gets the value of the treeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTreeAddress() {
        return treeAddress;
    }

    /**
     * Sets the value of the treeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTreeAddress(String value) {
        this.treeAddress = value;
    }

    public boolean isSetTreeAddress() {
        return (this.treeAddress!= null);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        if (name == null) {
            return "_NO_NAME_";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        if (description == null) {
            return "";
        } else {
            return description;
        }
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    public boolean isSetDescription() {
        return (this.description!= null);
    }

    /**
     * Gets the value of the exclusive property.
     * 
     * @return
     *     possible object is
     *     {@link TaskExclusivity }
     *     
     */
    public TaskExclusivity getExclusive() {
        if (exclusive == null) {
            return TaskExclusivity.NON_EXCLUSIVE;
        } else {
            return exclusive;
        }
    }

    /**
     * Sets the value of the exclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskExclusivity }
     *     
     */
    public void setExclusive(TaskExclusivity value) {
        this.exclusive = value;
    }

    public boolean isSetExclusive() {
        return (this.exclusive!= null);
    }

}
