//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 10:17:24 AM CEST 
//


package cz.cuni.mff.been.jaxb.td;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import cz.cuni.mff.been.jaxb.AbstractSerializable;


/**
 * <p>Java class for TaskPropertyObjects complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaskPropertyObjects">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://been.mff.cuni.cz/taskmanager/td}taskPropertyObject" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaskPropertyObjects", propOrder = {
    "taskPropertyObject"
})
public class TaskPropertyObjects
    extends AbstractSerializable
    implements Serializable
{

    private final static long serialVersionUID = -9223372036854775808L;
    protected List<TaskPropertyObject> taskPropertyObject;

    /**
     * Gets the value of the taskPropertyObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taskPropertyObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaskPropertyObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaskPropertyObject }
     * 
     * 
     */
    public List<TaskPropertyObject> getTaskPropertyObject() {
        if (taskPropertyObject == null) {
            taskPropertyObject = new ArrayList<TaskPropertyObject>();
        }
        return this.taskPropertyObject;
    }

    public boolean isSetTaskPropertyObject() {
        return ((this.taskPropertyObject!= null)&&(!this.taskPropertyObject.isEmpty()));
    }

    public void unsetTaskPropertyObject() {
        this.taskPropertyObject = null;
    }

}
