//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 10:17:23 AM CEST 
//


package cz.cuni.mff.been.jaxb.properties;

import javax.xml.bind.annotation.adapters.XmlAdapter;
import cz.cuni.mff.been.hostmanager.value.ValueVersion;

public class Adapter7
    extends XmlAdapter<String, ValueVersion>
{


    public ValueVersion unmarshal(String value) {
        return (cz.cuni.mff.been.hostmanager.value.ValueVersion.fromString(value));
    }

    public String marshal(ValueVersion value) {
        return (String.valueOf(value));
    }

}
