//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 10:17:23 AM CEST 
//


package cz.cuni.mff.been.jaxb.properties;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import cz.cuni.mff.been.jaxb.AbstractSerializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://been.mff.cuni.cz/hostmanager/properties}product"/>
 *         &lt;element ref="{http://been.mff.cuni.cz/hostmanager/properties}vendor" minOccurs="0"/>
 *         &lt;element ref="{http://been.mff.cuni.cz/hostmanager/properties}version" minOccurs="0"/>
 *         &lt;element ref="{http://been.mff.cuni.cz/hostmanager/properties}osRestriction" minOccurs="0"/>
 *         &lt;element ref="{http://been.mff.cuni.cz/hostmanager/properties}appRestriction"/>
 *       &lt;/all>
 *       &lt;attGroup ref="{http://been.mff.cuni.cz/hostmanager/properties}freeNameAttrGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "alias")
public class Alias
    extends AbstractSerializable
    implements Serializable
{

    private final static long serialVersionUID = -9223372036854775808L;
    @XmlElement(required = true)
    protected ChangedString product;
    protected ChangedString vendor;
    protected ChangedString version;
    protected Restriction osRestriction;
    @XmlElement(required = true)
    protected Restriction appRestriction;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link ChangedString }
     *     
     */
    public ChangedString getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangedString }
     *     
     */
    public void setProduct(ChangedString value) {
        this.product = value;
    }

    public boolean isSetProduct() {
        return (this.product!= null);
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link ChangedString }
     *     
     */
    public ChangedString getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangedString }
     *     
     */
    public void setVendor(ChangedString value) {
        this.vendor = value;
    }

    public boolean isSetVendor() {
        return (this.vendor!= null);
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link ChangedString }
     *     
     */
    public ChangedString getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangedString }
     *     
     */
    public void setVersion(ChangedString value) {
        this.version = value;
    }

    public boolean isSetVersion() {
        return (this.version!= null);
    }

    /**
     * Gets the value of the osRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link Restriction }
     *     
     */
    public Restriction getOSRestriction() {
        return osRestriction;
    }

    /**
     * Sets the value of the osRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Restriction }
     *     
     */
    public void setOSRestriction(Restriction value) {
        this.osRestriction = value;
    }

    public boolean isSetOSRestriction() {
        return (this.osRestriction!= null);
    }

    /**
     * Gets the value of the appRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link Restriction }
     *     
     */
    public Restriction getAppRestriction() {
        return appRestriction;
    }

    /**
     * Sets the value of the appRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Restriction }
     *     
     */
    public void setAppRestriction(Restriction value) {
        this.appRestriction = value;
    }

    public boolean isSetAppRestriction() {
        return (this.appRestriction!= null);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

}
