//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 10:17:23 AM CEST 
//


package cz.cuni.mff.been.jaxb.properties;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import cz.cuni.mff.been.jaxb.AbstractSerializable;


/**
 * <p>Java class for Complex complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Complex">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="remove" type="{http://been.mff.cuni.cz/hostmanager/properties}RemoveIndexed" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://been.mff.cuni.cz/hostmanager/properties}tree" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Complex", propOrder = {
    "remove",
    "subtrees"
})
public class Complex
    extends AbstractSerializable
    implements Serializable
{

    private final static long serialVersionUID = -9223372036854775808L;
    protected List<RemoveIndexed> remove;
    @XmlElement(name = "tree")
    protected List<Tree> subtrees;

    /**
     * Gets the value of the remove property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remove property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemove().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RemoveIndexed }
     * 
     * 
     */
    public List<RemoveIndexed> getRemove() {
        if (remove == null) {
            remove = new ArrayList<RemoveIndexed>();
        }
        return this.remove;
    }

    public boolean isSetRemove() {
        return ((this.remove!= null)&&(!this.remove.isEmpty()));
    }

    public void unsetRemove() {
        this.remove = null;
    }

    /**
     * Gets the value of the subtrees property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subtrees property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubtrees().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tree }
     * 
     * 
     */
    public List<Tree> getSubtrees() {
        if (subtrees == null) {
            subtrees = new ArrayList<Tree>();
        }
        return this.subtrees;
    }

    public boolean isSetSubtrees() {
        return ((this.subtrees!= null)&&(!this.subtrees.isEmpty()));
    }

    public void unsetSubtrees() {
        this.subtrees = null;
    }

}
