//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 10:17:23 AM CEST 
//


package cz.cuni.mff.been.jaxb.properties;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import cz.cuni.mff.been.jaxb.AbstractSerializable;


/**
 * <p>Java class for TheObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TheObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://been.mff.cuni.cz/hostmanager/properties}nvpsGroup"/>
 *       &lt;attGroup ref="{http://been.mff.cuni.cz/hostmanager/properties}objectAttrGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TheObject", propOrder = {
    "items"
})
public class TheObject
    extends AbstractSerializable
    implements Serializable
{

    private final static long serialVersionUID = -9223372036854775808L;
    @XmlElements({
        @XmlElement(name = "bool", type = NamedBoolean.class, nillable = true),
        @XmlElement(name = "rstring", type = NamedRangeString.class),
        @XmlElement(name = "rregexp", type = NamedRangeRegexp.class),
        @XmlElement(name = "regexp", type = NamedRegexp.class, nillable = true),
        @XmlElement(name = "lversion", type = NamedListVersion.class),
        @XmlElement(name = "lstring", type = NamedListString.class),
        @XmlElement(name = "int", type = NamedInt.class, nillable = true),
        @XmlElement(name = "rversion", type = NamedRangeVersion.class),
        @XmlElement(name = "rint", type = NamedRangeInt.class),
        @XmlElement(name = "ldouble", type = NamedListDouble.class),
        @XmlElement(name = "lint", type = NamedListInt.class),
        @XmlElement(name = "double", type = NamedDouble.class, nillable = true),
        @XmlElement(name = "string", type = NamedString.class, nillable = true),
        @XmlElement(name = "version", type = NamedVersion.class, nillable = true),
        @XmlElement(name = "lbool", type = NamedListBoolean.class),
        @XmlElement(name = "rbool", type = NamedRangeBoolean.class),
        @XmlElement(name = "lregexp", type = NamedListRegexp.class),
        @XmlElement(name = "rdouble", type = NamedRangeDouble.class)
    })
    protected List<AbstractSerializable> items;
    @XmlAttribute(name = "path", required = true)
    protected String path;

    /**
     * Gets the value of the items property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the items property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NamedBoolean }
     * {@link NamedRangeString }
     * {@link NamedRangeRegexp }
     * {@link NamedRegexp }
     * {@link NamedListVersion }
     * {@link NamedListString }
     * {@link NamedInt }
     * {@link NamedRangeVersion }
     * {@link NamedRangeInt }
     * {@link NamedListDouble }
     * {@link NamedListInt }
     * {@link NamedDouble }
     * {@link NamedString }
     * {@link NamedVersion }
     * {@link NamedListBoolean }
     * {@link NamedRangeBoolean }
     * {@link NamedListRegexp }
     * {@link NamedRangeDouble }
     * 
     * 
     */
    public List<AbstractSerializable> getItems() {
        if (items == null) {
            items = new ArrayList<AbstractSerializable>();
        }
        return this.items;
    }

    public boolean isSetItems() {
        return ((this.items!= null)&&(!this.items.isEmpty()));
    }

    public void unsetItems() {
        this.items = null;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    public boolean isSetPath() {
        return (this.path!= null);
    }

}
