//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 10:17:21 AM CEST 
//


package cz.cuni.mff.been.jaxb.group;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import cz.cuni.mff.been.common.rsl.Condition;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.cuni.mff.been.jaxb.group package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Rsl_QNAME = new QName("http://been.mff.cuni.cz/hostmanager/group", "rsl");
    private final static QName _Host_QNAME = new QName("http://been.mff.cuni.cz/hostmanager/group", "host");
    private final static QName _Desc_QNAME = new QName("http://been.mff.cuni.cz/hostmanager/group", "desc");
    private final static QName _Hosts_QNAME = new QName("http://been.mff.cuni.cz/hostmanager/group", "hosts");
    private final static QName _Meta_QNAME = new QName("http://been.mff.cuni.cz/hostmanager/group", "meta");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.cuni.mff.been.jaxb.group
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Host }
     * 
     */
    public Host createHost() {
        return new Host();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link MetaDesc }
     * 
     */
    public MetaDesc createMetaDesc() {
        return new MetaDesc();
    }

    /**
     * Create an instance of {@link Hosts }
     * 
     */
    public Hosts createHosts() {
        return new Hosts();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Condition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://been.mff.cuni.cz/hostmanager/group", name = "rsl")
    @XmlJavaTypeAdapter(Adapter1 .class)
    public JAXBElement<Condition> createRsl(Condition value) {
        return new JAXBElement<Condition>(_Rsl_QNAME, Condition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Host }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://been.mff.cuni.cz/hostmanager/group", name = "host")
    public JAXBElement<Host> createHost(Host value) {
        return new JAXBElement<Host>(_Host_QNAME, Host.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetaDesc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://been.mff.cuni.cz/hostmanager/group", name = "desc")
    public JAXBElement<MetaDesc> createDesc(MetaDesc value) {
        return new JAXBElement<MetaDesc>(_Desc_QNAME, MetaDesc.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Hosts }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://been.mff.cuni.cz/hostmanager/group", name = "hosts")
    public JAXBElement<Hosts> createHosts(Hosts value) {
        return new JAXBElement<Hosts>(_Hosts_QNAME, Hosts.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetaDesc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://been.mff.cuni.cz/hostmanager/group", name = "meta")
    public JAXBElement<MetaDesc> createMeta(MetaDesc value) {
        return new JAXBElement<MetaDesc>(_Meta_QNAME, MetaDesc.class, null, value);
    }

}
