//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 10:17:22 AM CEST 
//


package cz.cuni.mff.been.jaxb.pmc;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import cz.cuni.mff.been.jaxb.AbstractSerializable;


/**
 * <p>Java class for Java complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Java">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://been.mff.cuni.cz/pluggablemodule/config}classpathItems" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attGroup ref="{http://been.mff.cuni.cz/pluggablemodule/config}javaAttrGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Java", propOrder = {

})
public class Java
    extends AbstractSerializable
    implements Serializable
{

    private final static long serialVersionUID = -9223372036854775808L;
    protected ClassPathItems classpathItems;
    @XmlAttribute(name = "mainClass", required = true)
    protected String mainClass;

    /**
     * Gets the value of the classpathItems property.
     * 
     * @return
     *     possible object is
     *     {@link ClassPathItems }
     *     
     */
    public ClassPathItems getClasspathItems() {
        return classpathItems;
    }

    /**
     * Sets the value of the classpathItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassPathItems }
     *     
     */
    public void setClasspathItems(ClassPathItems value) {
        this.classpathItems = value;
    }

    public boolean isSetClasspathItems() {
        return (this.classpathItems!= null);
    }

    /**
     * Gets the value of the mainClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainClass() {
        return mainClass;
    }

    /**
     * Sets the value of the mainClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainClass(String value) {
        this.mainClass = value;
    }

    public boolean isSetMainClass() {
        return (this.mainClass!= null);
    }

}
