//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 10:17:22 AM CEST 
//


package cz.cuni.mff.been.jaxb.pmc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.cuni.mff.been.jaxb.pmc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Dependency_QNAME = new QName("http://been.mff.cuni.cz/pluggablemodule/config", "dependency");
    private final static QName _Dependencies_QNAME = new QName("http://been.mff.cuni.cz/pluggablemodule/config", "dependencies");
    private final static QName _ClasspathItem_QNAME = new QName("http://been.mff.cuni.cz/pluggablemodule/config", "classpathItem");
    private final static QName _Java_QNAME = new QName("http://been.mff.cuni.cz/pluggablemodule/config", "java");
    private final static QName _ClasspathItems_QNAME = new QName("http://been.mff.cuni.cz/pluggablemodule/config", "classpathItems");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.cuni.mff.been.jaxb.pmc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PluggableModuleConfiguration }
     * 
     */
    public PluggableModuleConfiguration createPluggableModuleConfiguration() {
        return new PluggableModuleConfiguration();
    }

    /**
     * Create an instance of {@link ClassPathItems }
     * 
     */
    public ClassPathItems createClassPathItems() {
        return new ClassPathItems();
    }

    /**
     * Create an instance of {@link Dependencies }
     * 
     */
    public Dependencies createDependencies() {
        return new Dependencies();
    }

    /**
     * Create an instance of {@link Java }
     * 
     */
    public Java createJava() {
        return new Java();
    }

    /**
     * Create an instance of {@link Dependency }
     * 
     */
    public Dependency createDependency() {
        return new Dependency();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Dependency }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://been.mff.cuni.cz/pluggablemodule/config", name = "dependency")
    public JAXBElement<Dependency> createDependency(Dependency value) {
        return new JAXBElement<Dependency>(_Dependency_QNAME, Dependency.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Dependencies }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://been.mff.cuni.cz/pluggablemodule/config", name = "dependencies")
    public JAXBElement<Dependencies> createDependencies(Dependencies value) {
        return new JAXBElement<Dependencies>(_Dependencies_QNAME, Dependencies.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://been.mff.cuni.cz/pluggablemodule/config", name = "classpathItem")
    public JAXBElement<String> createClasspathItem(String value) {
        return new JAXBElement<String>(_ClasspathItem_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Java }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://been.mff.cuni.cz/pluggablemodule/config", name = "java")
    public JAXBElement<Java> createJava(Java value) {
        return new JAXBElement<Java>(_Java_QNAME, Java.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassPathItems }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://been.mff.cuni.cz/pluggablemodule/config", name = "classpathItems")
    public JAXBElement<ClassPathItems> createClasspathItems(ClassPathItems value) {
        return new JAXBElement<ClassPathItems>(_ClasspathItems_QNAME, ClassPathItems.class, null, value);
    }

}
