//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 10:17:25 AM CEST 
//


package cz.cuni.mff.been.jaxb.tuplit;

import java.util.UUID;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter5
    extends XmlAdapter<String, UUID>
{


    public UUID unmarshal(String value) {
        return (java.util.UUID.fromString(value));
    }

    public String marshal(UUID value) {
        return (String.valueOf(value));
    }

}
